### PR TITLE
Use input instead of native click for table checkboxes. Fixes #81

### LINKED ISSUE #81: Checkable Table do not store the row when individual row is checked
### Overview of the problem

Just reproduce it here: https://oruga.io/components/Table.html#checkable
Browser:
- Edge: v88.0.705.56
- Chrome: v88.0.4324.104

### Description

When a single row is checked, the row is not pushed to checkedRows so it does not sync it at all (`Total checked` do not change)
However when  bulk rows are checked it works as expected.

### Steps to reproduce

Just reproduce it here: https://oruga.io/components/Table.html#checkable

Capture

(Thx for your amazing work)

### PR DESCRIPTION
**Pull request by astagi**
Fixes #81

### CODE REVIEW

File: packages/oruga/src/components/table/Table.vue [hunk 1]
```diff
@@ -170,7 +170,7 @@
                             <o-checkbox
                                 :disabled="!isRowCheckable(row)"
                                 :value="isRowChecked(row)"
-                                @click.native.prevent.stop="checkRow(row, index, $event)"
+                                @input="checkRow(row, index, $event)"
```
Comment (jtommy) [inline packages/oruga/src/components/table/Table.vue:173]: It's correct but we have to stop propagation otherwise the component will emit row click event

Comment (jtommy) [inline packages/oruga/src/components/table/Table.vue:173]: It's correct but we have to stop propagation otherwise the component will emit row click event

Comment (astagi) [reply packages/oruga/src/components/table/Table.vue:173]: Fixed modifying checkbox and radio propagation
